name: social_media_flutter
description: A package to integrate your Social Links widget easily in your mobile and webapps.
version: 0.0.2
homepage: https://github.com/akmadan/social_media_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: socialIcons
      fonts:
        - asset: packages/social_media_flutter/fonts/icons.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
